### ISSUE TITLE
App crashes when clicking Feed

### ISSUE THREAD

**Issue by evanz000** [AdevintaSpain/Barista#451]
Hey, awesome app, but now we can't access Feed, maybe instagram changed something. I cleared cache, logged out and in but it keeps crashing. Other tabs are fine.

Crash report below:

New Trace collected:
=====================
IMPORTANT: If sending by email, your email address and the entire content will be made public at https://github.com/austinhuang0131/barinsta/issues.

When possible, please describe the steps leading to this crash. Thank you for your cooperation.

Error report collected on: 2022-02-01T17:59:57.160

Information:
==============
VERSION		    : 19.2.4-fdroid
VERSION_CODE	: 65
PHONE-MODEL	    : Pixel 4 XL
ANDROID_VERS	: 11
ANDROID_REL	    : 30
BRAND			: google
MANUFACTURER	: Google
BOARD			: coral
DEVICE			: coral
PRODUCT		    : coral
HOST			: lineage-buildkite
TAGS			: release-keys

Stack:
==============
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String awais.instagrabber.repositories.responses.User.getUsername()' on a null object reference
	at awais.instagrabber.adapters.FeedStoriesAdapter.onBindViewHolder(FeedStoriesAdapter.java:15)
	at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:164)
	at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:9)
	at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1)
	at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:12)
	at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:119)
	at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:12)
	at androidx.recyclerview.widget.RecyclerView.onMeasure(RecyclerView.java:13)
	at android.view.View.measure(View.java:25466)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6957)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at com.google.android.material.appbar.CollapsingToolbarLayout.onMeasure(CollapsingToolbarLayout.java:2)
	at android.view.View.measure(View.java:25466)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6957)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
	at com.google.android.material.appbar.AppBarLayout.onMeasure(AppBarLayout.java:1)
	at android.view.View.measure(View.java:25466)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6957)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.onMeasureChild(CoordinatorLayout.java:1)
	at com.google.android.material.appbar.AppBarLayout$BaseBehavior.onMeasureChild(AppBarLayout.java:5)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.onMeasure(CoordinatorLayout.java:53)
	at android.view.View.measure(View.java:25466)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6957)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at android.view.View.measure(View.java:25466)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6957)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at android.view.View.measure(View.java:25466)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6957)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.onMeasure(CoordinatorLayout.java:54)
	at android.view.View.measure(View.java:25466)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6957)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at androidx.appcompat.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:21)
	at android.view.View.measure(View.java:25466)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6957)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at android.view.View.measure(View.java:25466)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6957)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at android.view.View.measure(View.java:25466)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6957)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
	at android.view.View.measure(View.java:25466)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6957)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at com.android.internal.policy.DecorView.onMeasure(DecorView.java:747)
	at android.view.View.measure(View.java:25466)
	at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:3402)
	at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:2246)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2504)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1948)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8177)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:972)
	at android.view.Choreographer.doCallbacks(Choreographer.java:796)
	at android.view.Choreographer.doFrame(Choreographer.java:731)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:957)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7664)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

*** End of current Report ***

**Comment by rocboronat** [comment]
Hello @evanz000 👋  Bad news. This is not the repo of the app you're using. If you want to know more, [check the readme of this project](https://github.com/AdevintaSpain/Barista). Hope you find the repo you're looking for! 😄
