### ISSUE TITLE
java.lang.SecurityException: Calling from not trusted UID! with 4.1.0 and + version

### ISSUE THREAD

**Issue by robertvargic** [AdevintaSpain/Barista#463]
**Library Version:**
4.1.0 and 4.2.0
  
**Describe the Bug:**
After the project is successfully compiled, running tests fails on the first test case. The stack trace doesn't show a crash, but by digging through the stack trace, I found some usable things, mainly related to the issue mentioned in the title. Rolling the project back to 4.0.0 fixes the issue, and I can run tests properly. This issue is not device dependent on my side since tests fail on real devices and multiple emulators.

**Stacktrace**
```
1-08 19:29:05.865 18316 18329 W Binder  : Caught a RuntimeException from the binder stub implementation.
11-08 19:29:05.865 18316 18329 W Binder  : java.lang.SecurityException: Calling from not trusted UID!
11-08 19:29:05.865 18316 18329 W Binder  : 	at android.app.UiAutomationConnection.throwIfCalledByNotTrustedUidLocked(UiAutomationConnection.java:525)
11-08 19:29:05.865 18316 18329 W Binder  : 	at android.app.UiAutomationConnection.shutdown(UiAutomationConnection.java:429)
11-08 19:29:05.865 18316 18329 W Binder  : 	at android.app.IUiAutomationConnection$Stub.onTransact(IUiAutomationConnection.java:390)
11-08 19:29:05.865 18316 18329 W Binder  : 	at android.os.Binder.execTransactInternal(Binder.java:1159)
11-08 19:29:05.865 18316 18329 W Binder  : 	at android.os.Binder.execTransact(Binder.java:1123)
```

**Comment by Sloy** [comment]
@robertvargic Is this the actual failure of the tests? It looks like a warning (W). Maybe there's another error in the log?
